version: "3.9"

services:
  ubuntu:
    image: ubuntu
    container_name: ubuntu-container
    working_dir: /tmp/python-code
    ports:
      - "8888:8888"
    volumes:
      - ./:/tmp/python-code
    command: sh -c "apt update && apt install -y python3 && python3 list-files.py"
    restart: unless-stopped
    network_mode: zoomcamp-network